### ISSUE TITLE
Point-LIO with flat mounted vs tilted lidar

### ISSUE THREAD

**Issue by migsdigs** [ctu-mrs/mrs_point_lio_core#6]
Hi there,

I was hoping you could help me answer some questions I have regarding my drone behavior when I mount the livox mid-360 tilted instead of flat mounted (have you ever mounted it at an angle?). In general I have very good performance using point-lio with the flat mounted lidar (very small amount of drift from groundtruth in simulation, can perform smooth path planning etc...). In simulation, when I pitch the lidar down (25 degrees), the odometry is initially good, but after some time the drone will start "flying away" while the odometry does not appear to change (remains close to the value where the drone began to rapidly fly away). Have you experienced anything similar?

For the simulation, the lidar source and lidar imu sit in the same frame, so I don't believe there is any problem with extrinsic settings (translation and rotation between lidar and imu should remain 0). One point of confusion is if I should alter the configuration parameters related to gravity:
```
    gravity_align: false # true to align the z axis of world frame with the direction of gravity, and the gravity direction should be specified below
    gravity: [0.0, 0.0, -9.810] # [0.0, 9.810, 0.0] # gravity to be aligned
    gravity_init: [0.0, 0.0, -9.810] # [0.0, 9.810, 0.0] # # preknown gravity in the first IMU body frame, use when imu_en is false or start from a non-stationary state
```

As the lidar IMU will now naturally not indicate -9.81 in the z direction.

Furthermore, I am curious as to why you set `gravity_align` to `false`. I have noticed slightly worse performance when it is set to `true` so I was wondering if you have determined this heuristically, or there is some other reason behind it.

For additional context, I have included the rest of my config file for point-lio:
```
common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    #    imu_topic: "/uav1/hw_api/imu"
    con_frame: false # true: if you need to combine several LiDAR frames into one
    con_frame_num: 1 # the number of frames combined
    cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
    cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency
    time_lag_imu_to_lidar: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)
    # the timesample of IMU is transferred from the current timeline to LiDAR's timeline by subtracting this value

preprocess:
    lidar_type: 1
    scan_line: 6
    timestamp_unit: 1           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 1.0                  # also from https://github.com/hku-mars/Point-LIO/issues/24, sometimes 0.5?

mapping:
    imu_en: true
    extrinsic_est_en: false # for aggressive motion, set this variable false
    imu_time_inte: 0.01 # = 1 / frequency of IMU
    satu_acc: 4.0 # the saturation value of IMU's acceleration. not related to the units # TODO: should be 4.0 not 30.0?
    satu_gyro: 35 # the saturation value of IMU's angular velocity. not related to the units
    acc_norm: 9.81 # 1.0 for g as unit, 9.81 for m/s^2 as unit of the IMU's acceleration
    lidar_meas_cov: 0.1 # 0.001; 0.01
    acc_cov_output: 500
    gyr_cov_output: 1000
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    imu_meas_acc_cov: 0.01 #0.1 # 0.1
    imu_meas_omg_cov: 0.1 #0.01 # 0.1
    gyr_cov_input: 0.01 # for IMU as input model
    acc_cov_input: 0.1 # for IMU as input model
    plane_thr: 0.05 # 0.05, the threshold for plane criteria, the smaller, the flatter a plane
    match_s: 81
    fov_degree: 360
    det_range: 50.0
    gravity_align: false # true to align the z axis of world frame with the direction of gravity, and the gravity direction should be specified below
    gravity: [0.0, 0.0, -9.810] # [0.0, 9.810, 0.0] # gravity to be aligned
    gravity_init: [0.0, 0.0, -9.810] # [0.0, 9.810, 0.0] # # preknown gravity in the first IMU body frame, use when imu_en is false or start from a non-stationary state
    # TODO: is this true for MID360 Livox?
    extrinsic_T: [ 0.0, 0.0, 0.0 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1 ]

#    extrinsic_T: [ 0.074, 0.0, 0.104 ]


odometry:
    publish_odometry_without_downsample: false

publish:
    path:
        enable: true # false: close the path output
        # TODO: use these values in code
        diff_t: 0.01 # (m) publish when translation has changed by this value
        diff_R: 0.01 # (rad) publish when one of the Euler angles has changed by this value
    scan_publish_en: true       # false: close all the point cloud output   TODO: might want to enable this and disable below
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file;
    # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
```

I would very much appreciate any feedback on this matter.

Kind regards,
Miguel
